name: limitless
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  splash_screen_view: ^3.0.0
  curved_navigation_bar: ^1.0.3
  shared_preferences: ^2.0.15
  date_time_picker: ^2.1.0
  dio: ^4.0.6
  rflutter_alert: ^2.0.4

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  image_path: 'assets/icon/icon.jpg'
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/icon/icon.jpg


